project:
  type: website

execute:
  freeze: auto

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true

toc: true
toc-title: "Innhold"
collapse-level: 1

website:
  title: "Dapla-manual"
  image: images/dapla-long.png
  favicon: images/dapla-favicon.png
  repo-url: https://github.com/statisticsnorway/dapla-manual
  open-graph: true
  search:
    location: sidebar
  page-footer:
    center: |
      Kom i gang med Dapla
  navbar:
    logo: images/dapla-long.png
    # Colour is "Dark 1" from https://design.ssb.no/#/components/color
    background: "#F0F8F9"
    # Colour is "Dark 5" from https://design.ssb.no/#/components/color
    foreground: "#274247"
    right:
      - icon: people-fill
        href: https://start.dapla.ssb.no/
        text: Opprette Dapla-team
        aria-label: Opprette Dapla-team
      - icon: question-lg
        href: https://web.yammer.com/main/org/ssb.no/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI5MDUzMjA2In0/all
        text: Stille spørsmål
      - icon: send-fill
        href: https://ssb.pureservice.com/#/new/7
        text: Melde sak
        aria-label: Åpne en sak hos Kundeservice
      - icon: github
        href: https://github.com/statisticsnorway/dapla-manual
        aria-label: Dapla-manual GitHub
  sidebar:
    collapse-level: 1
    contents:
      - href: index.qmd
      - href: preface.qmd
      - section: introduksjon.qmd
        contents:
          - hva-er-dapla.qmd
          - systemoversikt.qmd
          - innlogging.qmd
          - jupyterlab.qmd
      - section: statistikkproduksjon.qmd
        contents:
        - section: dapla-team.qmd
          contents: 
          - hva-er-dapla-team.qmd
          - administrasjon-av-team.qmd
        - gcc.qmd
        - overføring-av-data.qmd
        - section: produksjonsløp.qmd
          contents: 
          - jobbe-med-kode.qmd
          - jobbe-med-data.qmd
          - section: standarder.qmd
            contents:
              - datatilstander.qmd
              - navnestandard-datalagring.qmd
              - versjonering-av-datasett.qmd
          - orkestrering.qmd
          - koble-data.qmd
          - section: kildedata.qmd
            contents: 
            - automatisering.qmd
            - automatisering-avansert.qmd
          - statistikkbanken.qmd
          - arkivering.qmd
      - section: visualisering.qmd
        contents:
        - dashboard.qmd
        - lage-nettsider.qmd
      - section: bakkesystemer.qmd
        contents:
        - sas.qmd
        - oracle.qmd
        - pakke-install-bakken.qmd
      - section: annet.qmd
        contents:
        - git-og-github.qmd
        - lokale-utviklingsmiljøer.qmd
        - datadoc.qmd
        - github-app-integrasjon.qmd
        - gjenopprette-data.qmd
        - pakke-install.qmd
        - spark.qmd
        - slette-data.qmd
        - altinn3.qmd
        - kartdata.qmd
      - ordforklaringer.qmd
