project:
  type: book
  output-dir: ../docs

book:
  title: "Kom i gang med DAPLA"
  author: "Øyvind Bruer-Skarsbø"
  date: "10/9/2022"
  search: true
  cover-image: images/Dapla-Logo1.png
  repo-url: https://github.com/statisticsnorway/dapla-manual
  chapters:
    - index.qmd
    - preface.qmd
    - part: basics.qmd
      chapters:
      - intro.qmd
      - bakke-vs-sky.qmd
      - dapla-team.qmd
      - koding.qmd
      - egne-tjenester.qmd
    - part: advanced.qmd
      chapters:
      - databaser.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt

toc: true
toc-title: "Innhold"

comments:
  hypothesis: true



