project:
  type: book
  output-dir: ../docs

book:
  title: "Kom i gang med DAPLA"
  author: "Øyvind Bruer-Skarsbø"
  date: "10/9/2022"
  search: true
  cover-image: images/Dapla-Logo1.png
  repo-url: https://github.com/statisticsnorway/dapla-manual
  chapters:
    - index.qmd
    - preface.qmd
    - part: introduksjon.qmd
      chapters:
      - hva-er-dapla.qmd
      - hvorfor-dapla.qmd
      - arkitektur.qmd
      - innlogging.qmd
      - jupyterlab.qmd
      - bakke-sky.qmd
    - part: dapla-team.qmd
      chapters:
      - hva-er-dapla-team.qmd
      - opprette-dapla-team.qmd
      - gcc.qmd
      - lagre-data.qmd
      - hente-data.qmd
      - bakke-til-sky.qmd
      - administrasjon.qmd
    - part: beste-praksis.qmd
      chapters:
      - ssb-project.qmd
      - git-github.qmd
      - virtual-env.qmd
      - jupyter-kernel.qmd
      - pakke-install.qmd
      - samarbeid.qmd
      - vedlikehold.qmd
    - part: jupyter-pa-bakken.qmd
      chapters:
      - lese-data-bakken.qmd
    - part: avansert.qmd
      chapters:
      - remote.qmd
      - schedulering.qmd
      - databaser.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt

toc: true
toc-title: "Innhold"

comments:
  hypothesis: true



