# Administrasjon av team

I dette kapitlet viser vi hvordan du kan opprette et nytt team eller gjøre endringer i et eksisterende team. Typiske endringer er å: 

- Legge til eller fjerne medlemmer i et team
- Liste ut medlemmer og tilgangsgrupper i et team

## Opprette Dapla-team

For å komme i gang med å opprette et Dapla-team trengs det en oversikt over teamets medlemmer og hvilke tilgangsgrupper medlemmene skal være med i. Det trengs også informasjon om hvilke Dapla-tjenester som er aktuelle for teamet å ta i bruk. Derfor har det blitt opprettet en egen veileder for dette kalt *Dapla Start*.

::: {.callout-note appearance="simple"}
Gå til [Dapla Start](https://start.dapla.ssb.no) for starte bestilling av et nytt Dapla-team.
:::

Når teamet er opprettet får alle medlemmene tilgang til sitt eget prosjekt i Google Cloud Platform (GCP), som er SSBs leverandør av skytjenester. Videre får hvert prosjekt et sett med tjenester og tilganger som knyttes til teamet. Det opprettes også datalagringsområder (ofte kalt *bøtter*) som bare kan aksesseres av brukere som er med i teamets tilgangsgrupper.

Dapla-teamet vil også få sin egen gruppe i SSBs Active Directory slik at medlemskapet i gruppen kan administreres av Kundeservice.

## Legge til eller fjerne medlemmer i et team

For å legge til eller fjerne medlemmer i et team må du foreløpig opprette en [Kundeservice-sak](https://ssb.pureservice.com/#/new/7). Send en e-post til Kundeservice eller registrer en sak i portalen deres med følgende innhold:

- Navnet på Dapla-teamet du ønsker tilgang
- Hvilken tilgang du søker om. Typisk er det enten *data-admins*, *developers* eller *consumers*). [Les mer om hva de ulike tilgangene innebærer her](./hva-er-dapla-team.html#tbl-tilgangsroller). 
- Beskrivelse av formålet med tilgangen. 

Endringer i team må godkjennes av søker seksjonsleder før de blir effektuert.

For fjerning av tilganger kan man sende en tilsvarende henvendelse, men man trenger ikke inkludere forklaring av formål.  

::: {.callout-note}
## Midlertidig løsning

At endringer i team må gjøres via Kundeservice er midlertidig. Det jobbes med å lage et eget verktøy for dette.
:::

## Se medlemmer og roller i et team

For å se hvem som har de ulike tilgangsrollene i et team, så kan man bruke pakken [dapla-team-cli](https://pypi.org/project/dapla-team-cli/) fra Jupyter. Pakken er installert for alle og du kan liste ut medlemmer av team ved å gjøre følgende: 

1. [Logg deg inn på Dapla](./innlogging.html).
2. Åpne en ny terminal
3. Skriv inn `dpteam groups list-members` og trykk *Enter*
4. I prompten som dukker opp skriver du inn team-navn og trykker *Enter*. 

Hvis du ikke har [lagret Personal Access Token](./git-og-github.html#personal-access-token-(pat)) i Jupyter så blir du spurt om GitHub-bruker og passord etter punkt 4. Da oppgir du du bare din GitHub-bruker og [token som er autentisert mot statisticsnorway](./git-og-github.html#koble-deg-til-ssb).  


For de som ikke har mulighet til å bruke Jupyter så kan man også sende inn en forespørsel til *Kundeservice* om å få en oversikt. 
