---
from: markdown+emoji
---
# Bidra til Dapla-manualen

Alle i SSB kan bidra til denne manualen. Endringer må godkjennes av noen i [Team Statistikktjenester](https://github.com/orgs/statisticsnorway/teams/team-statistikktjenester), si gjerne i fra at det ligger en PR å se på.

::: {.callout-warning}
Denne nettsiden er åpen og hvem som helst kan lese det som er skrevet her. Hold det i tankene når du skriver.
:::

## Forutsetninger

- Man trenger basis git kompetanse, det ligger en fin beskrivelse av det på [Beste Praksis siden fra KVAKK](https://statistics-norway.atlassian.net/l/cp/6H4MD86J).
- Man trenger en konto på Github, det kan man opprette ved å [følge instruksjonene her](./git-github.html#opprett-github-bruker).
- Man kan lære seg Markdown (enkel tekst formatering), en fin oversikt [finnes her](http://mdcheatsheet.com/).
- Verktøyet Quarto burde installeres for å kunne se endringene slik som de ser ut på nettsiden. [Installasjon instruksjoner finnes her](https://quarto.org/docs/get-started/index.html).

## Fremgangsmåten

1. Klone repoet `git clone https://github.com/statisticsnorway/dapla-manual.git`
1. Lage en ny gren
1. Gjøre endringen
1. Kjør `quarto preview dapla-manual` og følge lenken for å sjekke at alt ser bra ut på nettsiden
1. Åpne en PR
1. Be noen å gjennomgå endringen og eventuelt godkjenne den
1. Merge PRen
1. Etter et par minutter skal din endring være synlig! :tada:
