# Forord {.unnumbered}

Denne boken tar sikte p친 친 gi SSB-ansatte mulighet til 친 ta i bruk grunnleggende funksjonalitet p친 DAPLA uten hjelp fra *eksperter*. Boken er bygget opp som den reisen vi mener en statistikker skal gjennom n친r de flytter sin produksjon fra bakke til sky^[I denne boken omtaler vi den gamle produksjonssonen, ofte kalt prodsonen, som **bakke**, og det nye skymilj칮et Google Cloud som **sky**. Det er ikke helt presist men duger for form친lene i denne boken.]. F칮rste del inneholder en del grunnleggende kunnskap som vi mener er viktig 친 ha f칮r man skal starte 친 jobbe i skyen. Andre del forklarer hvordan man s칮ker om 친 opprette et Dapla-team, en forutsetning for 친 drive databehandling p친 plattformen. Det vil ofte v칝re f칮rste steget i ta i bruk plattformen, siden det er slik man f친r et sted 친 lagre data. Her forklarer vi hvilke tjenester som inkluderes i et statistikkteam og hvordan man bruker og administerer dem. Den tredje delen tar utgangspunkt i at man skal starte 친 kode opp sin statistikkproduksjon eller kj칮re eksisterende kode. *ssb-project* er et verkt칮y som er utviklet i SSB for 친 gj칮re denne prosessen s친 enkel som mulig. Da kan brukerne implementere det som anses som god praksis i SSB med noen f친 tastetrykk, samtidig som vi ogs친 forklarer mer detaljert hva som skjer *under panseret*.

Det er tilrettelagt for en *treningsarena* i bakkemilj칮et. Dette milj칮et er nesten identisk med det som m칮ter deg p친 Dapla, med unntak av at du her har tilgang til mange av de gamle systemene og mye mindre *hestekrefter* i maskinene. Ideen er at SSB-ere ofte vil 칮nske 친 l칝re seg de nye verkt칮yene^[Det som omtales som *nye verkt칮y* er vil som regel bety R, Python, Git, GitHub og Jupyterlab.] i kjente og kj칝re omgivelser f칮rst, og deretter flytte et ferdig skrevet produksjonsl칮p til Dapla. Del 4 av denne boken beskriver mer utfyllende hvordan dette milj칮et skiller seg fra Dapla, og hvordan man gj칮r en del vanlige operasjoner mot de *gamle* bakkesystemene. 

Siste delen av boken kaller vi **Avansert** og tar for seg ulike emner som mer avanserte brukere typisk trenger informasjon om. Her finner man blant annet informasjon om hvilke databaser man kan bruke og hvilke form친l de er egnet for. Her beskrives ogs친 hvordan man kan bruke andre IDE-er enn Jupyterlab hvis man 칮nsker det. Tjenester for schedulerte kj칮ringer av Notebooks blir ogs친 diskutert.

Forh친pentligvis senker denne boken terskelen for 친 ta i bruk Dapla. Kommentarer og 칮nsker vedr칮rende boken tas imot med 친pne armer.

God forn칮yelse游때